collections:
  episodes:
    output: true

defaults:
  -
    scope:
      path: ""
      type: episodes
    values:
      layout: episode

# https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true
